#!/usr/bin/env python3

import argparse
import json
import math
import os
import readline
import sys
import traceback

from cc_pathlib import Path

import structarray

import numpy as np
import matplotlib.pyplot as plt
import mplcursors

data_pth = Path("/home/local_data/x601969/record/pflight/MFCPFLIGHT/c28fd6e6ec1c2c66/20251217_163311.reb")
meta_pth = Path("/dk/fdat18785/x601969/smartfly//source/mfcpflight_code/mapping/compact_map.tsv")


if __name__ == '__main__' :


	print("data: ",data_pth)
	print("meta: ",meta_pth)

	#load data
	#u = structarray.RebHandler().load(data_pth, meta_pth)
	u = structarray.open(data_pth, meta)
	t = u["_L33_MfcPflight.timestamp"]
	
	plt.plot(t[1:] - t[:-1])
	plt.show()

	"""
	R_HtaAltaRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaAltaRef"
	R_HtaVzRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaVzRef"
	R_HtaFpaRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaFpaRef"
	R_ObstFpa = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstFpa"
	R_ObstVz = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstVz"
	R_ObstAlt = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstAlt"
	R_HcGs = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I1_R_Vx"	
	R_HcVz = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I2_R_Vz"
	R_HcAlt = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I3_R_Z"
	R_HcFpa = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS.R_HcCurrFpa"


	

	fig0 = plt.figure(figsize = (8, 6))
	fig0.suptitle(" Altitude ")
	plt.plot(u[R_HtaAltaRef])
	plt.plot(u[R_ObstAlt])
	plt.plot(u[R_HcAlt])
	


	###############################################################################
	#    Planche 1
	###############################################################################

	fig1 = plt.figure(figsize=(8, 6))
	fig1.suptitle(" TerrainAvoid ")	
	# Creating a subfigure for the first and second row
	gs = plt.GridSpec(1, 3)
	gs.update(wspace=0.4, hspace=0.4)	
	row0fig0     = fig1.add_subplot(gs[0, 0])
	row0fig1     = fig1.add_subplot(gs[0, 1])
	row0fig2     = fig1.add_subplot(gs[0, 2])	
	ax = row0fig0
	ax.set_title('Altitude')
	ax.plot(u[R_HtaAltaRef], label="Ref")
	ax.plot(u[R_ObstAlt],label="Obst")
	ax.plot(u[R_HcAlt],label="Hc")
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	##letter_annotation(ax, -.25, 1, 'A')	
	ax = row0fig1
	ax.plot(u[R_HtaFpaRef],label="Ref")
	ax.plot(u[R_ObstFpa],label="Obst")
	ax.plot(u[R_HcFpa],label="Hc")
	ax.set_title('FPA')
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	##letter_annotation(ax, -.25, 1, 'B')	

	ax = row0fig2
	ax.plot(u[R_HtaVzRef],label="Ref")
	ax.plot(u[R_ObstVz],label="Obst")
	ax.plot(u[R_HcVz],label="Hc")
	ax.set_title('Vz')
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	#letter_annotation(ax, -.25, 1, 'C')	
	plt.show()"""
	
