#!/usr/bin/env python3

import argparse
import json
import math
import os
import readline
import sys
import traceback

from cc_pathlib import Path

import structarray

import numpy as np
import matplotlib.pyplot as plt
import mplcursors

data_pth = Path("jerruei.reb")
meta_pth = Path("tutu.tsv")

def find_delay(signal1, signal2):
    """
    Finds the delay between two signals by finding the peak
    of their first derivative (the rising edge).
    """
    
    # 1. Calculate the first derivative of each signal
    # This finds the point of maximum change (the edge)
    deriv1 = np.diff(signal1)
    deriv2 = np.diff(signal2)
    
    # 2. Find the index of the peak of the derivative
    edge_index1 = np.argmax(deriv1)
    edge_index2 = np.argmax(deriv2)
    
    # 3. The delay is the difference in these indices
    t_offset = -(edge_index2 - edge_index1)
    
    return t_offset

def clean_label(k_map) :
	s_map = {k : '.'.join(v).lstrip('_') for k, v in k_map.items()}
	try :
		if len(k_map) > 1 :
			while True :
				k_set = {v[0] for k, v in k_map.items()}
				if len(k_set) == len(k_map) :
					k_map = {k : v[1:] for k, v in k_map.items()}
				else :
					break

		return {k : '.'.join(v[-3:]).lstrip('_') for k, v in k_map.items()}
	except :
		return s_map

def ispi(line) :
	name = line.split('.')[-1]
	return ('psi' in name or 'trk' in name or 'argument' in name or 'dir' in name or 'drift' in name) and 'psidot' not in name and 'psiddot' not in name

class PlotSA() :
	def __init__(self, data_pth, meta_pth, bookmark_dir, data2_pth=None, meta2_pth=None, trigger = None) :
		self.data_pth = data_pth
		self.meta_pth = meta_pth
		self.bookmark_dir = bookmark_dir
		self.data2_pth = data2_pth
		self.meta2_pth = meta2_pth
		self.t_offset = 0.0
		self.trigger = trigger #"_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS.B_SetHOVER" #None

		self.load()
		#self.run()

	def load(self) :
		self.sa = structarray.RebHandler().load(self.data_pth, self.meta_pth)

		time_lst = sorted((len(var), var) for var in self.sa.meta.search('time_ms'))

		if time_lst :
			self.t_arr = self.sa[time_lst[0][1]]
		else :
			self.t_arr = np.arange(len(self.sa))

		print(f'time: {self.t_arr[0]} .. {self.t_arr[-1]}')
		self.sa2 = None
		if(self.data2_pth is not None and self.meta2_pth is not None):
			self.sa2 = structarray.RebHandler().load(self.data2_pth, self.meta2_pth)
			if time_lst :
				self.t2_arr = self.sa2[time_lst[0][1]]
			else :
				self.t2_arr = np.arange(len(self.sa2))

			self.t_offset = 304.8 - 212.7
			if (self.trigger is  not None):
				self.t_offset = find_delay(self.sa[self.trigger],self.sa2[self.trigger])
			print("t_offset",self.t_offset)
			self.t2_arr = self.t2_arr + self.t_offset 
			print(f'time: {self.t2_arr[0]} .. {self.t2_arr[-1]}')

	def run(self) :
		r_lst = list()
		while True :
			try:
				ans = input(">>> ").strip()
				if not ans :
					continue
				if ans.startswith('!') :
					if ans.startswith('!q') :
						sys.exit(0)
					if ans.startswith('!r') :
						self.load()
				elif ans.startswith("@") :
					bookmark_pth = bookmark_dir / f"{ans[1:]}.json"
					if bookmark_pth.is_file() :
						p_lst = bookmark_pth.load()
						self.plot(p_lst, ans[1:].replace("_", " ").title().strip())
					else :
						print(f"file not found: {bookmark_pth}")
						print('\n'.join(sorted(p.fname for p in bookmark_dir)))

				elif ans.startswith('&') :
					if ans == '&' :
						ans = '&0'
					try :
						if '.' in ans[1:] :
							print("time")
							n = np.where(self.t_arr == float(ans[1:]))[0]
						else :
							print("index")
							n = int(ans[1:])
					except ValueError :
						return
					print(n)
					# n = min(self.sa.length - 1, n)
					
					for name in r_lst :
						y_val = self.sa[name][n]
						if ispi(name) :
							if self.sa.meta[name][0] == 'Z4' :
								y_val = 360.0 * y_val.astype(np.double) / 0x100000000
							y_val = (y_val + 360.0) % 360.0
							y_val = np.where(y_val > 180.0, y_val - 360.0, y_val)

							
						print(f"{name} = {y_val}")

				elif ans.startswith('#') :
					if ans == '#' :
						ans = '#' + ';'.join(n_lst[i] for i in range(min(20, len(r_lst))))
					print(ans)
					p_lst = list()
					for p in ans[1:].split(';') :
						g_lst = list()
						for g in p.split() :
							try :
								g_lst.append([r_lst[n_lst.index(g)], None, None, None, None])
							except :
								print(g, n_lst)
								raise
						p_lst.append(g_lst)
					self.plot(p_lst)
				elif ans.startswith('?') :
					r_lst = self.sa.meta.search(ans[1:], mode='regexp')
					print('\n'.join(f'{n_lst[i]}. {var}' for i, var in enumerate(r_lst[:32])))
					if len(r_lst) >= 32 :
						print('...')
				else : # default to blob research mode
					r_lst = self.sa.meta.search(ans)
					print('\n'.join(f'{n_lst[i]}. {var}' for i, var in enumerate(r_lst[:32])))
					if len(r_lst) >= 32 :
						print('...')
			except Exception as e: 
				print("FATAL error occured \n ",e)
				print(traceback.format_exc())
				print("--------------------------------------")

	def plot(self, p_lst, title=None) :

		print(json.dumps(p_lst, indent='\t'))
		print(json.dumps(p_lst, indent='\t'))
		
		#get figure meta
		if isinstance(p_lst[0], dict) :
			meta = p_lst.pop(0)
		else :
			meta = dict()
		
		if 'col' in meta :
			n_col = meta['col']
			n_row = int(math.ceil(len(p_lst) / n_col))
		else :
			n_col, n_row = 1, len(p_lst)
		if 'size' in meta :
			size = tuple(meta['size'])
		else :
			size = (8,6)
			
		#create figure
		if title is not None :
			fig = plt.figure(title, figsize = size)
			fig.suptitle(title)
		else :
			fig = plt.figure(figsize = size)

		k_map = dict()
		for g_lst in p_lst :
			if isinstance(g_lst[0], dict) :
				g_lst = g_lst[1:]
			for name, color, opacity, width, format in g_lst :
				k_map[name] = name.split('.')
		k_map = clean_label(k_map)

		for i, g_lst in enumerate(p_lst) :
			if i == 0 :
				z = plt.subplot(n_row, n_col, i+1)
				q = z
				if len(p_lst) > 1 :
					plt.setp(z.get_xticklabels(), visible=False)
			else :
				q = plt.subplot(n_row, n_col, i+1, sharex=z)
				if i+1 < len(p_lst) :
					plt.setp(q.get_xticklabels(), visible=False)
			y_lst = list()

			# get figure parameters
			if isinstance(g_lst[0], dict) :
				fig_param = g_lst.pop(0)
			else :
				fig_param = dict()
			q.update(fig_param)

			for name, color, opacity, width, format in g_lst :
				m = dict()
				m['label'] = k_map[name]
				if color is not None :
					m['color'] = color
				if width is not None :
					m['linewidth'] = width
				if opacity is not None :
					m['alpha'] = opacity
				if name.startswith('*') :
					try :
						name = self.sa.meta.search(name[1:], mode='blob')[0]
					except :
						print(f"can not find var {name}")
				elif name.startswith('?') :
					name = self.sa.meta.search(name[1:], mode='regexp')[0]
				if name in self.sa.meta :
					y_arr = self.sa[name]
					if self.sa2 is not None:
						y2_arr = self.sa2[name]
					if ispi(name) :
						if self.sa.meta[name][0] == 'Z4' :
							y_arr = 360.0 * y_arr.astype(np.double) / 0x100000000
							if self.sa2 is not None:
								y2_arr = 360.0 * y_arr.astype(np.double) / 0x100000000
						y_arr = np.unwrap((y_arr + 360.0) % 360.0, 360.0)
						y_arr = np.where(y_arr > 180.0, y_arr - 360.0, y_arr)
						if self.sa2 is not None:
							y2_arr = np.unwrap((y2_arr + 360.0) % 360.0, 360.0)
							y2_arr = np.where(y2arr > 180.0, y2_arr - 360.0, y2_arr)
					if format is None :
						plt.plot(self.t_arr, y_arr, ** m)
						if self.sa2 is not None:
							m['label'] = k_map[name]+"2"
							plt.plot(self.t2_arr, y2_arr, ** m)
					else :
						plt.plot(self.t_arr, y_arr, format, ** m)
						if self.sa2 is not None:
							m['label'] = k_map[name]+"2"
							plt.plot(self.t2_arr, y2_arrr, format, ** m)
					y_lst.append(y_arr)
					if self.sa2 is not None:
						y_lst.append(y2_arr)
				else :
					print(self.sa.meta)
					print(f"{name} not found")
					print('\n'.join(self.sa.meta.search(name)))
				print(m)

			try :
				y_max = max(np.max(y) for y in y_lst)
				y_min = min(np.min(y) for y in y_lst)

				if 0 <= y_min and y_max <= 1 and ( 0.5 <= abs(y_max - y_min) or abs(y_max - y_min) == 0.0 ) :
					q.set_ylim([-0.5, +1.5])
				# elif y_max <= 12.0 :
				# 	y_min = min(0.0, y_min)
				# 	q.set_ylim([y_min-0.5, y_max+0.5])
			except ValueError :
				pass

			plt.grid()
			plt.legend()

		# fig.tight_layout()
		plt.show(block=False)


if __name__ == '__main__' :
	bookmark_dir = Path(os.environ.get("STRUCTARRAY_bookmark_DIR", "")).resolve()
	print(bookmark_dir)

	n_lst = '0123456789abcdefijklmnpqrstuvxyz'

	parser = argparse.ArgumentParser(description='Convert a meta (*.sam.tsv) and data (*.sad.bin) file into a tsv file')
	
	parser.add_argument('meta', metavar='META', type=Path, nargs='?', default=None, help='the meta (*.tsv) file')
	parser.add_argument('data', metavar='DATA', type=Path, nargs='?',  help='the data (*.reb) file')

	p = parser.parse_args()

	print("data: ",p.data)
	print("meta: ",p.meta)

	data_pth = (p.data).resolve()

	if p.meta is None :
		meta_pth = Path("context_map.tsv").resolve()
	else :
		meta_pth = (p.meta).resolve()


	print("data: ",data_pth)
	print("meta: ",meta_pth)

	#load data
	u2 = structarray.RebHandler().load(data_pth2, meta_pth2)

	
	R_HtaAltaRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaAltaRef"
	R_HtaVzRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaVzRef"
	R_HtaFpaRef = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._O0_S_HtaToRef.R_HtaFpaRef"
	R_ObstFpa = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstFpa"
	R_ObstVz = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstVz"
	R_ObstAlt = "_L222_MfcAfcs.S_AcqB1ToS.S_AcqObst.R_ObstAlt"
	R_HcGs = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I1_R_Vx"	
	R_HcVz = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I2_R_Vz"
	R_HcAlt = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS._I3_R_Z"
	R_HcFpa = "_C_1_RtmSchNomFctS._C_7_UpmS._C_2_UpmMgmS._C_1_UpmMgmTerrainS.R_HcCurrFpa"


	

	fig0 = plt.figure(figsize = (8, 6))
	fig0.suptitle(" Altitude ")
	plt.plot(u[R_HtaAltaRef])
	plt.plot(u[R_ObstAlt])
	plt.plot(u[R_HcAlt])
	


	###############################################################################
	#    Planche 1
	###############################################################################

	fig1 = plt.figure(figsize=(8, 6))
	fig1.suptitle(" TerrainAvoid ")	
	# Creating a subfigure for the first and second row
	gs = plt.GridSpec(1, 3)
	gs.update(wspace=0.4, hspace=0.4)	
	row0fig0     = fig1.add_subplot(gs[0, 0])
	row0fig1     = fig1.add_subplot(gs[0, 1])
	row0fig2     = fig1.add_subplot(gs[0, 2])	
	ax = row0fig0
	ax.set_title('Altitude')
	ax.plot(u[R_HtaAltaRef], label="Ref")
	ax.plot(u[R_ObstAlt],label="Obst")
	ax.plot(u[R_HcAlt],label="Hc")
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	##letter_annotation(ax, -.25, 1, 'A')	
	ax = row0fig1
	ax.plot(u[R_HtaFpaRef],label="Ref")
	ax.plot(u[R_ObstFpa],label="Obst")
	ax.plot(u[R_HcFpa],label="Hc")
	ax.set_title('FPA')
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	##letter_annotation(ax, -.25, 1, 'B')	

	ax = row0fig2
	ax.plot(u[R_HtaVzRef],label="Ref")
	ax.plot(u[R_ObstVz],label="Obst")
	ax.plot(u[R_HcVz],label="Hc")
	ax.set_title('Vz')
	ax.grid()        
	ax.legend(loc='upper right', bbox_to_anchor=(1.2, 1))
	#ax.set(xlabel=xlabel, ylabel=ylabel)
	#letter_annotation(ax, -.25, 1, 'C')	
	plt.show()
	