#!/usr/bin/env python3
"""
    Plot terrain avoidance profile form afcs recorder data
"""
import argparse
import json
import math
import os
import readline
import sys
import traceback

from cc_pathlib import Path

import structarray

import numpy as np
import matplotlib.pyplot as plt
import mplcursors

data_pth = Path("/mnt/afcs_data/record/terrain/eval/20260211_142319.rez")
data2_pth = None

R_GeoCoordLsb = 0.009313225746
R_GeoLatLonLsb = 8.381903172e-8

def plot_geo_meters(lats, lons, altitudes, label = None, new_plot = None, scatter_plot = True , pos_ref = None, offset = 0):
    """
    Plots geo-points on a 2D plane in meters relative to the start point.
    """

    # Pick a reference point (the first point or the mean)
    if pos_ref is None:
        ref_lat = lats[0]
        ref_lon = lons[0]
    else:
        ref_lat = pos_ref[0]
        ref_lon = pos_ref[1]

    # Project to Meters
    north_meters = (lats - ref_lat) * R_GeoCoordLsb

    # X must be scaled by the cosine of the latitude
    cos_lat = np.cos(np.radians(ref_lat*R_GeoLatLonLsb))
    east_meters = (lons - ref_lon) * R_GeoCoordLsb * cos_lat

    # 4. Create the Plot
    if new_plot is None:
        plt.figure(figsize=(10, 8))

    # Using 'terrain' colormap for altitude
    if scatter_plot:
        scatter = plt.scatter(east_meters, north_meters, c=altitudes, cmap='terrain',
                          edgecolors='black', linewidth=0.1, s=20)
        plt.colorbar(scatter, label='Altitude (m)')
        plt.axis('equal')
    else:
        #plt.plot(east_meters, north_meters)
        plt.plot(np.sqrt(east_meters**2+north_meters**2)+offset,altitudes, label=label)

    # Formatting
    plt.ylabel('Altitude (m)')
    plt.xlabel('GPS distance from start (meters)')
    plt.title('Local Planar Projection (Equirectangular)')
    plt.grid(True, linestyle=':', alpha=0.7)
    plt.legend()





if __name__ == '__main__' :

    parser = argparse.ArgumentParser(description='Plot terrain data from afcs recorder')
    parser.add_argument('data', metavar='DATA', default=data_pth, type=Path, help='the data (*.reb) file', nargs='?')
    parser.add_argument('--comp', '-c', metavar='DATA2', default=None, type=Path, help='the data2 (*.reb) file to compare against')

    p = parser.parse_args()

    data_pth = Path(p.data).resolve()
    map_id = str(data_pth).split('/')[-2]
    meta_pth = Path(f"/dk/fdat18785/x601969/smartfly/source/mfc_conan/model/MfcAfcs/mapping/compact_map.{map_id}.tsv")

    print("data: ",data_pth)
    print("meta: ",meta_pth)
    if p.comp is not None:
        data2_pth = Path(p.comp).resolve()
        map2_id = str(data2_pth).split('/')[-2]
        meta2_pth = Path(f"/dk/fdat18785/x601969/smartfly/source/mfc_conan/model/MfcAfcs/mapping/compact_map.{map2_id}.tsv")
        print("data2: ",data2_pth)
        print("meta2: ",meta2_pth)

    #load data
    u = structarray.open(data_pth, meta_pth)

    #t = u["_L33_MfcPflight.timestamp"]
    #plt.plot(t[1:] - t[:-1])
    #plt.show()

    aircraft_lats = u["S_AcqB.S_SenData.S_GpsRedChA.I_LatHel"]
    aircraft_lons = u["S_AcqB.S_SenData.S_GpsRedChA.I_LonHel"]
    aircraft_alts = u["_C_1_RtmSchNomFctS.S_CdtToMgm_P.R_ZBiC"]
    init_pos_ref = (aircraft_lats[0],aircraft_lons[0])
    plot_geo_meters(aircraft_lats, aircraft_lons, aircraft_alts, label = "Hel", scatter_plot = False)

    #route_lats = u["_C_1_RtmSchNomFctS.S_AcqObst.I_RouteLat"]
    #route_lons = u["_C_1_RtmSchNomFctS.S_AcqObst.I_RouteLon"]
    #plot_geo_meters(route_lats, route_lons, aircraft_alts*0+aircraft_alts[0], new_plot=False, scatter_plot = False, pos_ref=(aircraft_lats[0],aircraft_lons[0]), offset = 0)

    route_offset = u["_C_1_RtmSchNomFctS.S_AcqObst.R_ObstDist"]
    obstacle_lats = u["_C_1_RtmSchNomFctS.S_AcqObst.I_ObstLat"]
    obstacle_lons = u["_C_1_RtmSchNomFctS.S_AcqObst.I_ObstLon"]
    obstacle_alts = u["_C_1_RtmSchNomFctS.S_AcqObst.R_ObstAlt"]

    plot_geo_meters(obstacle_lats, obstacle_lons, obstacle_alts, new_plot=False, label = "Terr", scatter_plot = False, pos_ref=init_pos_ref, offset = route_offset)

    if(data2_pth is not None):
        u2 = structarray.open(data2_pth, meta2_pth)

        aircraft_lats = u2["S_AcqB.S_SenData.S_GpsRedChA.I_LatHel"]
        aircraft_lons = u2["S_AcqB.S_SenData.S_GpsRedChA.I_LonHel"]
        aircraft_alts = u2["_C_1_RtmSchNomFctS.S_CdtToMgm_P.R_ZBiC"]

        plot_geo_meters(aircraft_lats, aircraft_lons, aircraft_alts, label = "Hel2", new_plot=False, scatter_plot = False, pos_ref=init_pos_ref)

        #route_lats = u2["_C_1_RtmSchNomFctS.S_AcqObst.I_RouteLat"]
        #route_lons = u2["_C_1_RtmSchNomFctS.S_AcqObst.I_RouteLon"]
        #plot_geo_meters(route_lats, route_lons, aircraft_alts*0+aircraft_alts[0], new_plot=False, scatter_plot = False, pos_ref=(aircraft_lats[0],aircraft_lons[0]), offset = 0)

        route_offset = u2["_C_1_RtmSchNomFctS.S_AcqObst.R_ObstDist"]
        obstacle_lats = u2["_C_1_RtmSchNomFctS.S_AcqObst.I_ObstLat"]
        obstacle_lons = u2["_C_1_RtmSchNomFctS.S_AcqObst.I_ObstLon"]
        obstacle_alts = u2["_C_1_RtmSchNomFctS.S_AcqObst.R_ObstAlt"]

        plot_geo_meters(obstacle_lats, obstacle_lons, obstacle_alts, new_plot=False, label = "Terr2", scatter_plot = False, pos_ref=init_pos_ref, offset = route_offset)
        #plot_geo_meters(obstacle_lats, obstacle_lons, obstacle_alts, new_plot=False, scatter_plot = False)#, pos_ref=(aircraft_lats[0],obstacle_lons[0]))




    plt.show()


