#!/usr/bin/env bash

source_DIR=$(realpath $(dirname ${BASH_SOURCE[0]}))

function push_pythonpath() {
	pth=$1:A
	echo "+ ${pth}"
	export PATH=${pth}/script:$PATH
	export PYTHONPATH=${pth}/package:$PYTHONPATH
}

push_pythonpath ${source_DIR}

export STRUCTARRAY_build_DIR=${source_DIR}/build

export STRUCTARRAY_bookmark_DIR=${source_DIR}/data/upmv
