#!/usr/bin/env python3

import argparse

from cc_pathlib import Path

from structarray.rebin import RebHandler

parser = argparse.ArgumentParser(description='Convert a .reb file to .rez')

parser.add_argument('data', metavar='DATA', type=Path, help='the data (*.reb) file')
parser.add_argument('--meta', metavar='META', type=Path, help='the meta (*.tsv) file, load mapping.tsv by default')

p = parser.parse_args()

reb = RebHandler(cache_disabled=True).load(p.data, p.meta)
reb.to_rez()
