#!/usr/bin/env python3

import re
import sys

from cc_pathlib import Path

from structarray.parself2 import ElfParser

pth = Path(sys.argv[1]).resolve()
info = ElfParser(pth)

nam = sys.argv[2]
meta = info.get_meta(f"_C_{nam}", remove=re.compile(f'_{nam}\\b'))
#meta = info.get_meta(f"node_context", remove=re.compile(f'_{nam}\\b'))

meta.dump(pth.parent / f"context_map.{nam}.tsv", False, False)
