#!/usr/bin/env python3

import argparse

from cc_pathlib import Path

import structarray

parser = argparse.ArgumentParser(description='Convert a meta (*.sam.tsv) and data (*.sad.bin) file into a tsv file')

parser.add_argument('meta', metavar='META', type=Path, help='the meta (*.tsv) file')
parser.add_argument('data', metavar='DATA', type=Path, help='the data (*.reb) file')

parser.add_argument('--filter', metavar='FILTER', type=Path, help='the filter (*.tsv) file')

p = parser.parse_args()

u = structarray.StructArray(p.meta, p.data)

context_pth = p.data.with_suffix('.context.tsv')
if not context_pth.is_file() :
	u.to_tsv(p.data.with_suffix('.context.tsv'))
	u.to_listing(p.data.with_suffix('.listing.tsv'))


print(
	u['_C_3_upmv_core._C_1_D__root__._C_2_D_lon_override.is_override'][:128]
)

print(
	u['_C_3_upmv_core._C_1_D__root__._C_2_D_lon_override._L273_upmv_app']
)

import matplotlib.pyplot as plt

plt.plot(u['_C_3_upmv_core._C_1_D__root__._C_2_D_lon_override._L223_upmv_app'])
plt.show()