#!/usr/bin/env python3

import argparse
import sys

from cc_pathlib import Path

import structarray

parser = argparse.ArgumentParser(description='Try to identify the source of inf or nan in a record')

parser.add_argument('data', metavar='DATA', type=Path, nargs='+', help='the data (*.reb) file')
parser.add_argument('--meta', metavar='META', type=Path, default=None, help='the meta (*.tsv) file')

p = parser.parse_args()

for data_pth in p.data :
	u = structarray.open(data_pth, p.meta)
	u.debug()
